services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lab'
      - 'POSTGRES_PASSWORD=belcaid2001'
      - 'POSTGRES_USER=belcaid'
    ports:
      - '5432'
    networks:
      - 'spring-cloud-network'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=pgadmin@example.com' # Set your preferred email
      - 'PGADMIN_DEFAULT_PASSWORD=pgadminPassword' # Set your preferred password
      - 'PGADMIN_LISTEN_PORT=5050'
    ports:
      - '5050:5050' # Map port 5050 on the host to port 80 on the container
    networks:
      - 'spring-cloud-network'


networks:
  spring-cloud-network:
    driver: bridge


