# Database config for PostgreSQL
DB_TYPE: postgresql
DB_USERNAME: belcaid
DB_PASSWORD: belcaid2001
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: Lab-Management
DB_DRIVER: org.postgresql.Driver
DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect

#server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev
