package com.labmanagement.model.enums;

public enum ExpressionBesoinType {
	  	PARTICIPATION_FEES,
	    SMALL_TOOLS_EQUIPMENT_PURCHASE,
	    COMPUTER_SUPPLIES_PURCHASE,
	    OFFICE_SUPPLIES_PURCHASE,
	    RAW_MATERIALS_PURCHASE,
	    TRAVEL_EXPENSES_ABROAD,
	    TRAVEL_EXPENSES_IN_COUNTRY,
	    KILOMETER_ALLOWANCE,
	    MISSION_EXPENSES_ABROAD,
	    FUEL_PURCHASE,
	    SCIENTIFIC_EQUIPMENT_PURCHASE,
	    COMPUTER_EQUIPMENT_PURCHASE,
}
